API stands for Application Programming Interface and is a software intermediary that allows two applications to talk to each other.

The advantages of using APIs:

Automation : Less human effort is required and workflows can be easily updated to become faster and more
productive.

Efficiency : It allows to use the capabilities of one of the already developed APIs than to try to independently implement some functionality from scratch.

The disadvantage of using APIs:

Security: If the API is poorly integrated, it means it will be vulnerable to attacks, resulting in data breeches or losses having financial or reputation implications.

One of the applications we will use in this notebook is Random User Generator. RandomUser is an open-source, free API providing developers with randomly generated users to be used as placeholders for testing purposes. This makes the tool similar to Lorem Ipsum, but is a placeholder for people instead of text. The API can return multiple results, as well as specify generated user details such as gender, email, image, username, address, title, first and last name, and more.

Another example of simple API we will use in this notebook is Fruitvice application. The Fruitvice API webservice which provides data for all kinds of fruit! You can use Fruityvice to find out interesting information about fruit and educate yourself. The webservice is completely free to use and contribute to.

RandomUser API:
Bellow are Get Methods parameters that we can generate.

get_cell()

get_city()

get_dob()

get_email()

get_first_name()

get_full_name()

get_gender()

get_id()

get_id_number()

get_id_type()

get_info()

get_last_name()

get_login_md5()

get_login_salt()

get_login_sha1()

get_login_sha256()

get_nat()

get_password()

get_phone()

get_picture()

get_postcode()

get_registered()

get_state()

get_street()

get_username()

get_zipcode()

In [1]:
!pip install randomuser

Collecting randomuser
  Downloading randomuser-1.6.tar.gz (5.0 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: randomuser
  Building wheel for randomuser (setup.py): started
  Building wheel for randomuser (setup.py): finished with status 'done'
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5092 sha256=35cc7cd382c00a792dae8e8675b6c66141642dbaad016161102c525bc9a2322e
  Stored in directory: c:\users\004in2744\appdata\local\pip\cache\wheels\8e\47\49\3724182e7f2e58cbf9b02c1ac1ed51b769cb62cf0ab3a1ee4e
Successfully built randomuser
Installing collected packages: randomuser
Successfully installed randomuser-1.6

In [2]:
from randomuser import RandomUser
import pandas as pd

In [3]:
r = RandomUser()

Then, using generate_users() function, we get a list of random 10 users

In [4]:
some_list = r.generate_users(10)
some_list

[<randomuser.RandomUser at 0x1997b779e70>,
 <randomuser.RandomUser at 0x1997b779ae0>,
 <randomuser.RandomUser at 0x1997b778670>,
 <randomuser.RandomUser at 0x1997b778820>,
 <randomuser.RandomUser at 0x1997b77a8c0>,
 <randomuser.RandomUser at 0x1997b76cfd0>,
 <randomuser.RandomUser at 0x1997b76ce50>,
 <randomuser.RandomUser at 0x1997b76e980>,
 <randomuser.RandomUser at 0x1997b76f850>,
 <randomuser.RandomUser at 0x1997b76c700>]

The "Get Methods" functions mentioned at the beginning of this notebook, can generate the required parameters to construct a dataset. For example, to get full name, we call get_full_name() function.

In [5]:
name = r.get_full_name()

Let's say we only need 10 users with full names and their email addresses. We can write a "for-loop" to print these 10 users

In [6]:
for user in some_list:
    print (user.get_full_name()," ",user.get_email())

August Christiansen   august.christiansen@example.com
Daimen Vogelezang   daimen.vogelezang@example.com
Aquino Porto   aquino.porto@example.com
Edith Reynolds   edith.reynolds@example.com
Väinö Korpi   vaino.korpi@example.com
Debbie Peters   debbie.peters@example.com
محیا كامياران   mhy.kmyrn@example.com
Rosa Blanco   rosa.blanco@example.com
Perpétuo Almeida   perpetuo.almeida@example.com
Felix Olson   felix.olson@example.com

In [7]:
# generate photos of the random 5 users.

for user in some_list:
    print (user.get_picture())

https://randomuser.me/api/portraits/men/95.jpg
https://randomuser.me/api/portraits/men/78.jpg
https://randomuser.me/api/portraits/men/45.jpg
https://randomuser.me/api/portraits/women/57.jpg
https://randomuser.me/api/portraits/men/39.jpg
https://randomuser.me/api/portraits/women/96.jpg
https://randomuser.me/api/portraits/women/24.jpg
https://randomuser.me/api/portraits/women/29.jpg
https://randomuser.me/api/portraits/men/33.jpg
https://randomuser.me/api/portraits/men/90.jpg

To generate a table with information about the users, we can write a function containing all desirable parameters. For example, name, gender, city, etc. The parameters will depend on the requirements of the test to be performed. We call the Get Methods, listed at the beginning of this notebook. Then, we return pandas dataframe with the users.

In [8]:
def get_users():
    users =[]
     
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
      
    return pd.DataFrame(users)

In [9]:
get_users()

,Name,Gender,City,State,Email,DOB,Picture
0,Nella Jarvi,female,Asikkala,Finland Proper,nella.jarvi@example.com,1945-12-23T21:09:07.594Z,https://randomuser.me/api/portraits/women/77.jpg
1,Alexander Wilson,male,Invercargill,Hawke'S Bay,alexander.wilson@example.com,1957-11-03T10:34:23.160Z,https://randomuser.me/api/portraits/men/26.jpg
2,Janete Moraes,female,Guarulhos,Minas Gerais,janete.moraes@example.com,1969-06-11T02:45:24.068Z,https://randomuser.me/api/portraits/women/76.jpg
3,Hervé Nguyen,male,Birmensdorf (Zh),Nidwalden,herve.nguyen@example.com,1997-02-19T21:57:34.857Z,https://randomuser.me/api/portraits/men/71.jpg
4,Ivy White,female,Wellington,Waikato,ivy.white@example.com,1995-05-23T01:58:31.276Z,https://randomuser.me/api/portraits/women/24.jpg
5,Mattie Wells,female,Albuquerque,West Virginia,mattie.wells@example.com,1987-08-29T11:45:52.135Z,https://randomuser.me/api/portraits/women/42.jpg
6,Annabelle Brown,female,Notre Dame de Lourdes,Manitoba,annabelle.brown@example.com,1980-05-04T13:58:51.887Z,https://randomuser.me/api/portraits/women/18.jpg
7,Klaus Schell,male,Bad Reichenhall,Brandenburg,klaus.schell@example.com,1953-09-20T02:58:16.730Z,https://randomuser.me/api/portraits/men/69.jpg
8,Thiago Fontai,male,Nancy,Oise,thiago.fontai@example.com,1970-06-11T19:12:37.656Z,https://randomuser.me/api/portraits/men/10.jpg
9,Nalan Sadıklar,female,Şanlıurfa,Tunceli,nalan.sadiklar@example.com,1952-02-08T15:42:08.099Z,https://randomuser.me/api/portraits/women/60.jpg

In [10]:
df1 = pd.DataFrame(get_users())
df1

,Name,Gender,City,State,Email,DOB,Picture
0,Lisa Jackson,female,Shiloh,Michigan,lisa.jackson@example.com,1970-07-09T16:23:47.085Z,https://randomuser.me/api/portraits/women/15.jpg
1,Philip Bergeron,male,Sutton,Newfoundland and Labrador,philip.bergeron@example.com,1960-11-30T07:56:29.088Z,https://randomuser.me/api/portraits/men/88.jpg
2,Sean Lane,male,Aubrey,Montana,sean.lane@example.com,1967-12-02T05:28:06.404Z,https://randomuser.me/api/portraits/men/92.jpg
3,Isaiah Powell,male,Trim,Monaghan,isaiah.powell@example.com,1945-05-21T00:22:24.284Z,https://randomuser.me/api/portraits/men/68.jpg
4,Ilyas Jeppesen,male,Flekkefjord,Akershus,ilyas.jeppesen@example.com,1945-08-07T03:50:01.170Z,https://randomuser.me/api/portraits/men/60.jpg
5,Tomothy Wright,male,Wagga Wagga,Northern Territory,tomothy.wright@example.com,1989-03-24T10:13:30.303Z,https://randomuser.me/api/portraits/men/87.jpg
6,Timothy Fabre,male,Mülligen,Genève,timothy.fabre@example.com,1966-03-22T11:42:43.350Z,https://randomuser.me/api/portraits/men/93.jpg
7,Caroline Lewis,female,Inverness,Avon,caroline.lewis@example.com,1959-03-14T18:02:57.436Z,https://randomuser.me/api/portraits/women/36.jpg
8,Clara Petersen,female,Sandved,Sjælland,clara.petersen@example.com,1976-02-08T19:02:52.842Z,https://randomuser.me/api/portraits/women/16.jpg
9,Phoebe Wagner,female,Brighton and Hove,County Antrim,phoebe.wagner@example.com,1946-01-13T04:10:53.387Z,https://randomuser.me/api/portraits/women/69.jpg

Another, more common way to use APIs, is through requests library. The next lab, Requests and HTTP, will contain more information about requests.

We will start by importing all required libraries.

In [11]:
import requests
import json

We will obtain the fruitvice API data using requests.get("url") function. The data is in a json format.

In [12]:
data = requests.get("https://fruityvice.com/api/fruit/all")

We will retrieve results using json.loads() function.

In [13]:
results = json.loads(data.text)

We will convert our json data into pandas data frame

In [14]:
pd.DataFrame(results)

,name,id,family,order,genus,nutritions
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,"{'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c..."
1,Strawberry,3,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
2,Banana,1,Musaceae,Zingiberales,Musa,"{'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c..."
3,Tomato,5,Solanaceae,Solanales,Solanum,"{'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca..."
4,Pear,4,Rosaceae,Rosales,Pyrus,"{'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c..."
5,Durian,60,Malvaceae,Malvales,Durio,"{'calories': 147, 'fat': 5.3, 'sugar': 6.75, '..."
6,Blackberry,64,Rosaceae,Rosales,Rubus,"{'calories': 40, 'fat': 0.4, 'sugar': 4.5, 'ca..."
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,"{'calories': 50, 'fat': 0.34, 'sugar': 5.74, '..."
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,"{'calories': 61, 'fat': 0.5, 'sugar': 9.0, 'ca..."
9,Lychee,67,Sapindaceae,Sapindales,Litchi,"{'calories': 66, 'fat': 0.44, 'sugar': 15.0, '..."
10,Pineapple,10,Bromeliaceae,Poales,Ananas,"{'calories': 50, 'fat': 0.12, 'sugar': 9.85, '..."
11,Fig,68,Moraceae,Rosales,Ficus,"{'calories': 74, 'fat': 0.3, 'sugar': 16.0, 'c..."
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,"{'calories': 44, 'fat': 0.6, 'sugar': 0.0, 'ca..."
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,"{'calories': 97, 'fat': 0.7, 'sugar': 11.2, 'c..."
14,Plum,71,Rosaceae,Rosales,Prunus,"{'calories': 46, 'fat': 0.28, 'sugar': 9.92, '..."
15,Orange,2,Rutaceae,Sapindales,Citrus,"{'calories': 43, 'fat': 0.2, 'sugar': 8.2, 'ca..."
16,GreenApple,72,Rosaceae,Rosales,Malus,"{'calories': 21, 'fat': 0.1, 'sugar': 6.4, 'ca..."
17,Raspberry,23,Rosaceae,Rosales,Rubus,"{'calories': 53, 'fat': 0.7, 'sugar': 4.4, 'ca..."
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,"{'calories': 30, 'fat': 0.2, 'sugar': 6.0, 'ca..."
19,Lemon,26,Rutaceae,Sapindales,Citrus,"{'calories': 29, 'fat': 0.3, 'sugar': 2.5, 'ca..."
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,"{'calories': 60, 'fat': 0.38, 'sugar': 13.7, '..."
21,Blueberry,33,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
22,Apple,6,Rosaceae,Rosales,Malus,"{'calories': 52, 'fat': 0.4, 'sugar': 10.3, 'c..."
23,Guava,37,Myrtaceae,Myrtales,Psidium,"{'calories': 68, 'fat': 1.0, 'sugar': 9.0, 'ca..."
24,Apricot,35,Rosaceae,Rosales,Prunus,"{'calories': 15, 'fat': 0.1, 'sugar': 3.2, 'ca..."
25,Papaya,42,Caricaceae,Caricacea,Carica,"{'calories': 43, 'fat': 0.4, 'sugar': 1.0, 'ca..."
26,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,"{'calories': 34, 'fat': 0.0, 'sugar': 8.0, 'ca..."
27,Tangerine,77,Rutaceae,Sapindales,Citrus,"{'calories': 45, 'fat': 0.4, 'sugar': 9.1, 'ca..."
28,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,"{'calories': 36, 'fat': 0.4, 'sugar': 3.0, 'ca..."
29,Lime,44,Rutaceae,Sapindales,Citrus,"{'calories': 25, 'fat': 0.1, 'sugar': 1.7, 'ca..."
30,Pomegranate,79,Lythraceae,Myrtales,Punica,"{'calories': 83, 'fat': 1.2, 'sugar': 13.7, 'c..."
31,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,"{'calories': 60, 'fat': 1.5, 'sugar': 8.0, 'ca..."
32,Grape,81,Vitaceae,Vitales,Vitis,"{'calories': 69, 'fat': 0.16, 'sugar': 16.0, '..."
33,Morus,82,Moraceae,Rosales,Morus,"{'calories': 43, 'fat': 0.39, 'sugar': 8.1, 'c..."
34,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,"{'calories': 44, 'fat': 0.4, 'sugar': 3.0, 'ca..."
35,Avocado,84,Lauraceae,Laurales,Persea,"{'calories': 160, 'fat': 14.66, 'sugar': 0.66,..."
36,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,"{'calories': 61, 'fat': 0.5, 'sugar': 8.9, 'ca..."
37,Cranberry,87,Ericaceae,Ericales,Vaccinium,"{'calories': 46, 'fat': 0.1, 'sugar': 4.0, 'ca..."
38,Cherry,9,Rosaceae,Rosales,Prunus,"{'calories': 50, 'fat': 0.3, 'sugar': 8.0, 'ca..."
39,Peach,86,Rosaceae,Rosales,Prunus,"{'calories': 39, 'fat': 0.25, 'sugar': 8.4, 'c..."
40,Jackfruit,94,Moraceae,Rosales,Artocarpus,"{'calories': 95, 'fat': 0.0, 'sugar': 19.1, 'c..."
41,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,"{'calories': 44, 'fat': 1.26, 'sugar': 0.5, 'c..."

The result is in a nested json format. The 'nutrition' column contains multiple subcolumns, so the data needs to be 'flattened' or normalized.

In [15]:
df2 = pd.json_normalize(results)
df2

,name,id,family,order,genus,nutritions.calories,nutritions.fat,nutritions.sugar,nutritions.carbohydrates,nutritions.protein
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,81,0.00,18.00,18.00,0.00
1,Strawberry,3,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.80
2,Banana,1,Musaceae,Zingiberales,Musa,96,0.20,17.20,22.00,1.00
3,Tomato,5,Solanaceae,Solanales,Solanum,74,0.20,2.60,3.90,0.90
4,Pear,4,Rosaceae,Rosales,Pyrus,57,0.10,10.00,15.00,0.40
5,Durian,60,Malvaceae,Malvales,Durio,147,5.30,6.75,27.10,1.50
6,Blackberry,64,Rosaceae,Rosales,Rubus,40,0.40,4.50,9.00,1.30
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,50,0.34,5.74,11.30,0.75
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,61,0.50,9.00,15.00,1.10
9,Lychee,67,Sapindaceae,Sapindales,Litchi,66,0.44,15.00,17.00,0.80
10,Pineapple,10,Bromeliaceae,Poales,Ananas,50,0.12,9.85,13.12,0.54
11,Fig,68,Moraceae,Rosales,Ficus,74,0.30,16.00,19.00,0.80
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,44,0.60,0.00,10.00,0.90
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,97,0.70,11.20,22.40,2.20
14,Plum,71,Rosaceae,Rosales,Prunus,46,0.28,9.92,11.40,0.70
15,Orange,2,Rutaceae,Sapindales,Citrus,43,0.20,8.20,8.30,1.00
16,GreenApple,72,Rosaceae,Rosales,Malus,21,0.10,6.40,3.10,0.40
17,Raspberry,23,Rosaceae,Rosales,Rubus,53,0.70,4.40,12.00,1.20
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,30,0.20,6.00,8.00,0.60
19,Lemon,26,Rutaceae,Sapindales,Citrus,29,0.30,2.50,9.00,1.10
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,60,0.38,13.70,15.00,0.82
21,Blueberry,33,Rosaceae,Rosales,Fragaria,29,0.40,5.40,5.50,0.00
22,Apple,6,Rosaceae,Rosales,Malus,52,0.40,10.30,11.40,0.30
23,Guava,37,Myrtaceae,Myrtales,Psidium,68,1.00,9.00,14.00,2.60
24,Apricot,35,Rosaceae,Rosales,Prunus,15,0.10,3.20,3.90,0.50
25,Papaya,42,Caricaceae,Caricacea,Carica,43,0.40,1.00,11.00,0.00
26,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,34,0.00,8.00,8.00,0.00
27,Tangerine,77,Rutaceae,Sapindales,Citrus,45,0.40,9.10,8.30,0.00
28,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,36,0.40,3.00,7.00,1.00
29,Lime,44,Rutaceae,Sapindales,Citrus,25,0.10,1.70,8.40,0.30
30,Pomegranate,79,Lythraceae,Myrtales,Punica,83,1.20,13.70,18.70,1.70
31,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,60,1.50,8.00,9.00,9.00
32,Grape,81,Vitaceae,Vitales,Vitis,69,0.16,16.00,18.10,0.72
33,Morus,82,Moraceae,Rosales,Morus,43,0.39,8.10,9.80,1.44
34,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,44,0.40,3.00,8.00,0.60
35,Avocado,84,Lauraceae,Laurales,Persea,160,14.66,0.66,8.53,2.00
36,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,61,0.50,8.90,14.60,1.14
37,Cranberry,87,Ericaceae,Ericales,Vaccinium,46,0.10,4.00,12.20,0.40
38,Cherry,9,Rosaceae,Rosales,Prunus,50,0.30,8.00,12.00,1.00
39,Peach,86,Rosaceae,Rosales,Prunus,39,0.25,8.40,9.50,0.90
40,Jackfruit,94,Moraceae,Rosales,Artocarpus,95,0.00,19.10,23.20,1.72
41,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,44,1.26,0.50,7.56,1.78

we need to know the family and genus of a cherry.

In [16]:
cherry = df2.loc[df2["name"] == 'Cherry']
(cherry.iloc[0]['family']) , (cherry.iloc[0]['genus'])

('Rosaceae', 'Prunus')

In [17]:
#ind out how many calories are contained in a banana.

cal_banana = df2.loc[df2["name"] == 'Banana']
cal_banana.iloc[0]['nutritions.calories']

96

In [18]:
data2 = requests.get("https://cat-fact.herokuapp.com/facts")

In [19]:
results2 = json.loads(data2.text)

In [20]:
results2

[{'status': {'verified': True, 'sentCount': 1},
  '_id': '58e00b5f0aac31001185ed24',
  'user': '58e007480aac31001185ecef',
  'text': 'When asked if her husband had any hobbies, Mary Todd Lincoln is said to have replied "cats."',
  '__v': 0,
  'source': 'user',
  'updatedAt': '2020-08-23T20:20:01.611Z',
  'type': 'cat',
  'createdAt': '2018-02-19T21:20:03.434Z',
  'deleted': False,
  'used': False},
 {'status': {'verified': True, 'feedback': '', 'sentCount': 1},
  '_id': '5887e1d85c873e0011036889',
  'user': '5a9ac18c7478810ea6c06381',
  'text': 'Cats make about 100 different sounds. Dogs make only about 10.',
  '__v': 0,
  'source': 'user',
  'updatedAt': '2020-09-03T16:39:39.578Z',
  'type': 'cat',
  'createdAt': '2018-01-15T21:20:00.003Z',
  'deleted': False,
  'used': True},
 {'status': {'verified': True, 'sentCount': 1},
  '_id': '58e008780aac31001185ed05',
  'user': '58e007480aac31001185ecef',
  'text': 'Owning a cat can reduce the risk of stroke and heart attack by a third.',
  '__v': 0,
  'source': 'user',
  'updatedAt': '2020-08-23T20:20:01.611Z',
  'type': 'cat',
  'createdAt': '2018-03-29T20:20:03.844Z',
  'deleted': False,
  'used': False},
 {'status': {'verified': True, 'sentCount': 1},
  '_id': '58e009390aac31001185ed10',
  'user': '58e007480aac31001185ecef',
  'text': "Most cats are lactose intolerant, and milk can cause painful stomach cramps and diarrhea. It's best to forego the milk and just give your cat the standard: clean, cool drinking water.",
  '__v': 0,
  'source': 'user',
  'updatedAt': '2020-08-23T20:20:01.611Z',
  'type': 'cat',
  'createdAt': '2018-03-04T21:20:02.979Z',
  'deleted': False,
  'used': False},
 {'status': {'verified': True, 'sentCount': 1},
  '_id': '58e00af60aac31001185ed1d',
  'user': '58e007480aac31001185ecef',
  'text': 'It was illegal to slay cats in ancient Egypt, in large part because they provided the great service of controlling the rat population.',
  '__v': 0,
  'source': 'user',
  'updatedAt': '2020-09-16T20:20:04.164Z',
  'type': 'cat',
  'createdAt': '2018-01-15T21:20:02.945Z',
  'deleted': False,
  'used': True}]

In [21]:
df3 = pd.DataFrame(results2)
df3.drop(columns="status",inplace=True)
df3

,_id,user,text,__v,source,updatedAt,type,createdAt,deleted,used
0,58e00b5f0aac31001185ed24,58e007480aac31001185ecef,"When asked if her husband had any hobbies, Mar...",0,user,2020-08-23T20:20:01.611Z,cat,2018-02-19T21:20:03.434Z,False,False
1,5887e1d85c873e0011036889,5a9ac18c7478810ea6c06381,Cats make about 100 different sounds. Dogs mak...,0,user,2020-09-03T16:39:39.578Z,cat,2018-01-15T21:20:00.003Z,False,True
2,58e008780aac31001185ed05,58e007480aac31001185ecef,Owning a cat can reduce the risk of stroke and...,0,user,2020-08-23T20:20:01.611Z,cat,2018-03-29T20:20:03.844Z,False,False
3,58e009390aac31001185ed10,58e007480aac31001185ecef,"Most cats are lactose intolerant, and milk can...",0,user,2020-08-23T20:20:01.611Z,cat,2018-03-04T21:20:02.979Z,False,False
4,58e00af60aac31001185ed1d,58e007480aac31001185ecef,"It was illegal to slay cats in ancient Egypt, ...",0,user,2020-09-16T20:20:04.164Z,cat,2018-01-15T21:20:02.945Z,False,True